# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3165526d2ccbc24363b57fc1cdb7993d65cfdf332a75c6c2a57242c1e6976704656c4291c6222a84e0c556074483930df460cbe104c6f312f1301bb421aac193

test:
  secret_key_base: ee1b63bb6815b2cb20baa42673267b6c9933d008ed4eeb621185b39982980c2220c645e12b357e592d1b3dc1864e8fc5ca5d539c88353cae3eef743e0e399477

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
